image: nexus.otpbank.com.ua:10443/repository/tools/docker:19.03.12

variables:
  http_proxy: http://chckproxy.raiffeisenbank.com.ua:8080
  https_proxy: http://chckproxy.raiffeisenbank.com.ua:8080
  no_proxy: "otpbank.com.ua,raiffeisenbank.com.ua,10.244.74.2,10.244.74.2,10.244.74.2,10.244.74.3,10.244.74.4,10.244.74.5,10.244.74.6,10.244.74.7,192.168.138.189,127.0.0.1,localhost,spiraapp"
  DOCKER_AUTH_CONFIG: "{\"auths\":{\"nexus.otpbank.com.ua:10443/repository/docker-hosted\":{\"auth\":\"$CI_DOCKER_AUTH\"}}}" 

stages:
  - build
  - deploy

build:
  stage: build
  image: 
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  environment:
    name: $ENVIRONMENT
  script:
    - echo "123"
  when: manual

deploy:
  stage: deploy
  image: nexus.otpbank.com.ua:10443/repository/tools/helm-kubectl:3.3.1
  before_script:
    - echo ${KUBECONFIG_CONTENT} | base64 -d > ${KUBECONFIG}
    - kubectl config use-context ${KUBE_CONTEXT}
  script:
    - echo "Apply"
  when: manual
