FROM python:3.10-alpine

ARG SETTINGS=""
ENV ARG_SETTINGS=$SETTINGS

WORKDIR /usr/src/wrapper

COPY cert.crt /usr/local/share/ca-certificates/cert.crt
RUN update-ca-certificates

COPY docker/wrapper/config.ini .
COPY docker/wrapper/wrapper.py .

CMD ["python3",  "wrapper.py", "${ARG_SETTINGS}"]