FROM python:3.10-alpine

ARG SETTINGS=""
ENV ARG_SETTINGS=$SETTINGS

WORKDIR /usr/src/wrapper

COPY docker/wrapper/config.ini .
COPY docker/wrapper/wrapper.py .

RUN if [ -f /vault/secrets/config.ini ]; then   cp -f /vault/secrets/config.ini /usr/src/wrapper/config.ini; fi

ENTRYPOINT ["python3",  "wrapper.py", "server.domain=wrapper", "${ARG_SETTINGS}"]
