FROM liquibase/liquibase

ADD db/src/main/resources/changelog /liquibase/changelog 

CMD ["sh", "-c", "docker-entrypoint.sh --url=${URL} --username=${USERNAME} --password=${PASSWORD} --classpath=/liquibase/changelog --changeLogFile=changelog/db.changelog-master.yaml update"]