podAnnotations:
  vault.hashicorp.com/agent-inject: "true"
  vault.hashicorp.com/agent-pre-populate-only: "true"
  vault.hashicorp.com/agent-init-first: "true"
  vault.hashicorp.com/auth-path: "auth/test-cluster"
  vault.hashicorp.com/agent-inject-secret-config.ini: "secret/data/antifraud/dev3/wrapper"
  vault.hashicorp.com/agent-inject-template-config.ini: |
    {{- with secret "secret/data/antifraud/dev3/wrapper" -}}
    {{ .Data.data.config }}
    {{- end }}
  vault.hashicorp.com/role: "antifraud-wrapper"

#volumes:
#- name: source
#  nfs:
#    path: /zpool8t/antifraud/dev3/wrapper/source
#    server: 10.244.14.30
#- name: files
#  nfs:
#    path: /zpool8t/antifraud/dev3/wrapper/files
#    server: 10.244.14.30
#
#volumeMounts:
#- name: source
#  mountPath: /source
#- name: files
#  mountPath: /usr/src/wrapper/files

persistentVolume:
  -  name: antifraud-wrapper-source
     storage: 200Gi
     storageClassName: default
     namespace: antifrauddev
     accessModes:
       - ReadWriteMany
     csi:
       driver: smb.csi.k8s.io
       readOnly: false
       volumeHandle: antifraud-wrapper-source
       volumeAttributes:
         source: "//uaatssrv02.raiffeisenbank.com.ua/antifraud/dev/wrapper/source"
       nodeStageSecretRef:
         name: antifraud-volume
         namespace: antifrauddev
  -  name: antifraud-wrapper-files
     storage: 200Gi
     storageClassName: default
     namespace: antifrauddev
     accessModes:
       - ReadWriteMany
     csi:
       driver: smb.csi.k8s.io
       readOnly: false
       volumeHandle: antifraud-wrapper-files
       volumeAttributes:
         source: "//uaatssrv02.raiffeisenbank.com.ua/antifraud/dev/wrapper/files"
       nodeStageSecretRef:
         name: antifraud-volume
         namespace: antifrauddev

persistentVolumeClaim:
  -  name: antifraud-wrapper-source
     storage: 200Gi
     storageClassName: default
     namespace: antifrauddev
     accessModes:
       - ReadWriteMany
  -  name: antifraud-wrapper-files
     storage: 200Gi
     storageClassName: default
     namespace: antifrauddev
     accessModes:
       - ReadWriteMany

volumeMounts:
- name: antifraud-wrapper-source
  mountPath: /source
- name: antifraud-wrapper-files
  mountPath: /usr/src/wrapper/files
volumes: 
- name: antifraud-wrapper-source
  persistentVolumeClaim:
    claimName: antifraud-wrapper-source
- name: antifraud-wrapper-files
  persistentVolumeClaim:
    claimName: antifraud-wrapper-files

namespace: antifrauddev
project: antifrauddev