podAnnotations:
  vault.hashicorp.com/agent-inject: "true"
  vault.hashicorp.com/agent-pre-populate-only: "true"
  vault.hashicorp.com/agent-init-first: "true"
  vault.hashicorp.com/auth-path: "auth/test-cluster"
  vault.hashicorp.com/agent-inject-secret-config.ini: "secret/data/antifraud/dev3/wrapper"
  vault.hashicorp.com/agent-inject-template-config.ini: |
    {{- with secret "secret/data/antifraud/dev3/wrapper" -}}
    {{ .Data.data.config }}
    {{- end }}
  vault.hashicorp.com/role: "antifraud-wrapper"

volumes:
- name: source
  nfs:
    path: /zpool8t/antifraud/dev3/wrapper/source
    server: 10.244.14.30
- name: files
  nfs:
    path: /zpool8t/antifraud/dev3/wrapper/files
    server: 10.244.14.30

volumeMounts:
- name: source
  mountPath: /source
- name: files
  mountPath: /usr/src/wrapper/files