  vault: 
    vaultTemplate: '{{- with secret  "secret/data/antifraud/uat/schedulertest/" }}{{ .Data.data.properties }}{{ end }}'
    vaultRole: "antifraud-schedulertest"
    vaultAddress: "https://vaulttest.otpbank.com.ua:443"
    vaultMountPath: "auth/test-cluster/"
    appPropertiesPath: "/vault/secrets/application.properties"