nameOverride: ""
fullnameOverride: ""

replicaCount: 1

spec:
  namespace: default
  rootnamespace: argocd
  project: antifraud
  repourl: "https://nexus.otpbank.com.ua:8443/repository/it-operations-helm"
  source:
    targetrevision:
      downloader: version
      import: version
      notification: version
      scheduler: version
      schedulertest: version
      web: version
    name:
      downloader: downloader
      import: import
      notification: notification
      scheduler: scheduler
      schedulertest: schedulertest
      web: web