nameOverride: ""
fullnameOverride: ""

replicaCount: 1

spec:
  destination:
    server: "https://kubernetes.default.svc"
  namespace: default
  rootnamespace: argocd
  repourl: "https://nexus.otpbank.com.ua:8443/repository/it-operations-helm"
  source:
    targetrevision:
      downloader: version
      dispatcher: version
      importer: version
      notification: version
      scheduler: version
      web: version
      dwh: version
      liquibase: version
      enricher: version
      statuslogger: version
      report: version
      wrapper: version
    name:
      downloader: downloader
      dispatcher: dispatcher
      importer: importer
      notification: notification
      scheduler: scheduler
      web: web
      dwh: dwh
      liquibase: liquibase
      enricher: enricher
      statuslogger: statuslogger
      report: report
      wrapper: wrapper