---
fullnameOverride: ""
imagePullSecrets: []
nameOverride: ""
replicaCount: 1
spec:
  destination:
    server: "https://kubernetes.default.svc"
  namespace: default
  rootnamespace: argocd
  project: antifraud
  repourl: "https://nexus.otpbank.com.ua:8443/repository/it-operations-helm"
  source:
    targetrevision:
      downloader: version
      import: version
      notification: version
      pipeline: version
      scheduler: version
      schedulertest: version
      web: version
    name:
      downloader: downloader
      import: import
      notification: notification
      pipeline: pipeline
      scheduler: scheduler
      schedulertest: schedulertest
      web: web