vault: 
    vaultTemplate: '{{- with secret  "secret/data/antifraud/uat/web/" }}{{ .Data.data.properties }}{{ end }}'
    vaultRole: "antifraud-web"
    vaultAddress: "https://vaulttest.otpbank.com.ua:443"
    vaultMountPath: "auth/uat-cluster/"
    appPropertiesPath: "/vault/secrets/application.properties"
  
ingress:
  enabled: true
  labels: {}
  annotations: 
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/secure-backends: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  path: /
  hosts:
    - antifraud-uat.otpbank.com.ua
  tls: []