vault:
    vaultTemplate: '{{- with secret  "secret/data/antifraud/uat/web/" }}{{ .Data.data.properties }}{{ end }}'
    vaultRole: "antifraud-web"
    vaultAddress: "https://vaulttest.otpbank.com.ua:443"
    vaultMountPath: "auth/uat-cluster/"
    appPropertiesPath: "/vault/secrets/application.properties"

ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: antifraud-uat.otpbank.com.ua
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
  - hosts:
    - antifraud-uat.otpbank.com.ua
    secretName: antifraud-tls