  vault: 
    vaultTemplate: '{{- with secret  "secret/data/antifraud/web/" }}{{ .Data.data.properties }}{{ end }}'
    vaultRole: "web"
    vaultAdress: "https://vault.otpbank.com.ua:443"
    vaultMountPath: "auth/kubernetes/"
    appPropertiesPath: "/vault/secrets/application.properties"