vault:
  vaultTemplate: '{{- with secret  "secret/data/antifraud/web/" }}{{ .Data.data.properties }}{{ end }}'
  vaultRole: "antifraud-web"
  vaultAddress: "https://vault.otpbank.com.ua:443"
  vaultMountPath: "auth/kubernetes/"
  appPropertiesPath: "/vault/secrets/application.properties"

ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: antifraud-prod.otpbank.com.ua
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
  - hosts:
    - antifraud-prod.otpbank.com.ua
    secretName: antifraud-tls

namespace: antifraud
project: antifraud