vault: 
  vaultTemplate: '{{- with secret  "secret/data/antifraud/uat/liquibase/" }}{{ .Data.data.properties }}{{ end }}'
  vaultRole: "antifraud-liquibase"
  vaultAddress: "https://vaulttest.otpbank.com.ua:443"
  vaultMountPath: "auth/uat-cluster/"
  appPropertiesPath: "/vault/secrets/liquibase.properties"