  vault: 
    vaultTemplate: '{{- with secret  "secret/data/antifraud/dev3/downloader/" }}{{ .Data.data.properties }}{{ end }}'
    vaultRole: "antifraud-liquibase"
    vaultAddress: "https://vaulttest.otpbank.com.ua:443"
    vaultMountPath: "auth/test-cluster/"
    appPropertiesPath: "/vault/secrets/application.properties"