apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "service.name" . }}
  namespace: {{ .Values.namespace }}
data:
  config-init.hcl: |-
    "auto_auth" = {
      "method" = {
        "config" = {
          "role" = {{ .Values.vault.vaultRole | quote }}
        }
        type = "kubernetes"
        "mount_path" = {{ .Values.vault.vaultMountPath | quote}}
      }
      "sink" = {
        "config" = {
          "path" = "/home/vault/.token"
        }
        "type" = "file"
      }
    }
    "exit_after_auth" = true
    "pid_file" = "/home/vault/.pid"
    "template" = {
     {{- toYaml .Values.vault.vaultTemplate | nindent 6 }}
     }
     
    "vault" = {
      "address" = {{ .Values.vault.vaultAddress | quote}}
    }