  vault:
    vaultTemplate: '{{- with secret  "secret/data/antifraud/report/" }}{{ .Data.data.properties }}{{ end }}'
    vaultRole: "antifraud-report"
    vaultAddress: "https://vault.otpbank.com.ua:443"
    vaultMountPath: "auth/kubernetes/"
    appPropertiesPath: "/vault/secrets/application.properties"