vault:
  vaultTemplate: '{{- with secret  "secret/data/antifraud/dev3/report/" }}{{ .Data.data.properties }}{{ end }}'
  vaultRole: "antifraud-report"
  vaultAddress: "https://vaulttest.otpbank.com.ua:443"
  vaultMountPath: "auth/test-cluster/"
  appPropertiesPath: "/vault/secrets/application.properties"

volumes:
- name: antifraud
  nfs:
    path: /zpool8t/antifraud/dev3/report
    server: 10.244.14.30
  
volumeMounts:
- name: antifraud
  mountPath: /opt

namespace: antifraud
project: antifraud