  vault:
    vaultTemplate: '{{- with secret  "secret/data/antifraud/uat/report/" }}{{ .Data.data.properties }}{{ end }}'
    vaultRole: "antifraud-report"
    vaultAddress: "https://vaulttest.otpbank.com.ua:443"
    vaultMountPath: "auth/uat-cluster/"
    appPropertiesPath: "/vault/secrets/application.properties"

#  volumes:
#  - name: antifraud
#    nfs:
#      path: /zpool8t/antifraud/uat/report
#      server: 10.244.14.30
#  
#  volumeMounts:
#  - name: antifraud
#    mountPath: /opt

persistentVolume:
  name: antifraud-report
  storage: 20Gi
  storageClassName: default
  namespace: antifrauduat
  accessModes:
    - ReadWriteMany
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: antifraud-report
    volumeAttributes:
      source: "//uaatssrv02.raiffeisenbank.com.ua/antifraud/uat"
    nodeStageSecretRef:
      name: antifraud-volume
      namespace: antifrauduat

persistentVolumeClaim:
  name: antifraud-report
  storage: 20Gi
  storageClassName: default
  namespace: antifrauduat
  accessModes:
    - ReadWriteMany

volumeMounts:
- name: antifraud-report
  mountPath: /opt
volumes: 
- name: antifraud-report
  persistentVolumeClaim:
    claimName: antifraud-report

  namespace: antifrauduat
  project: antifrauduat
