  vault:
    vaultTemplate: '{{- with secret  "secret/data/antifraud/uat/report/" }}{{ .Data.data.properties }}{{ end }}'
    vaultRole: "antifraud-report"
    vaultAddress: "https://vaulttest.otpbank.com.ua:443"
    vaultMountPath: "auth/uat-cluster/"
    appPropertiesPath: "/vault/secrets/application.properties"

  volumes:
  - name: antifraud
    nfs:
      path: /zpool8t/antifraud/uat/report/folder
      server: 10.244.14.30
  
  volumeMounts:
  - name: antifraud
    mountPath: /opt

  namespace: antifrauduat
  project: antifrauduat
