apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.persistentVolume.name }}
spec:
  storageClassName: {{ .Values.persistentVolume.storageClassName }}
  {{- with .Values.persistentVolume.csi }}   
  csi:
     {{- toYaml . | nindent 4 }}
  {{- end }} 
  {{- with .Values.persistentVolume.accessModes }}   
  accessModes:
     {{- toYaml . | nindent 4 }}
  {{- end }}