  vault: 
    vaultTemplate: '{{- with secret  "secret/data/antifraud/dev3/notification/" }}{{ .Data.data.properties }}{{ end }}'
    vaultRole: "notification"
    vaultAdress: "https://vaulttest.otpbank.com.ua:443"
    vaultMountPath: "auth/test-cluster/"
    appPropertiesPath: "/vault/secrets/application.properties"