vault: 
  vaultTemplate: '{{- with secret  "secret/data/antifraud/notification/" }}{{ .Data.data.properties }}{{ end }}'
  vaultRole: "antifraud-notification"
  vaultAddress: "https://vault.otpbank.com.ua:443"
  vaultMountPath: "auth/kubernetes/"
  appPropertiesPath: "/vault/secrets/application.properties"

#volumes:
#- name: antifraud
#  nfs:
#    path: /zpool8t/antifraud/prod
#    server: 10.244.14.30
#    
#volumeMounts:
#- name: antifraud
#  mountPath: /opt

persistentVolume:
  name: antifraud-notification
  storage: 500Gi
  storageClassName: default
  namespace: antifraudprod
  accessModes:
    - ReadWriteMany
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: antifraud-notification
    volumeAttributes:
      source: "//uaafis01.raiffeisenbank.com.ua/antifraud/prod"
    nodeStageSecretRef:
      name: antifraud-volume
      namespace: antifraudprod

persistentVolumeClaim:
  name: antifraud-notification
  storage: 500Gi
  storageClassName: default
  namespace: antifraudprod
  accessModes:
    - ReadWriteMany

volumeMounts:
- name: antifraud-notification
  mountPath: /opt
volumes: 
- name: antifraud-notification
  persistentVolumeClaim:
    claimName: antifraud-notification

namespace: antifraudprod
project: antifraudprod