  vault:
    vaultTemplate: '{{- with secret  "secret/data/antifraud/dev3/dwh/" }}{{ .Data.data.properties }}{{ end }}'
    vaultRole: "antifraud-dwh"
    vaultAddress: "https://vaulttest.otpbank.com.ua:443"
    vaultMountPath: "auth/test-cluster/"
    appPropertiesPath: "/vault/secrets/application.properties"

  namespace: antifrauddev
  project: antifrauddev