  vault: 
    vaultTemplate: '{{- with secret  "secret/data/antifraud/uat/enricher/" }}{{ .Data.data.properties }}{{ end }}'
    vaultRole: "antifraud-enricher"
    vaultAddress: "https://vaulttest.otpbank.com.ua:443"
    vaultMountPath: "auth/uat-cluster/"
    appPropertiesPath: "/vault/secrets/application.properties"