vault: 
  vaultTemplate: '{{- with secret  "secret/data/antifraud/uat/downloader/" }}{{ .Data.data.properties }}{{ end }}'
  vaultRole: "antifraud-downloader"
  vaultAddress: "https://vaulttest.otpbank.com.ua:443"
  vaultMountPath: "auth/uat-cluster/"
  appPropertiesPath: "/vault/secrets/application.properties"

volumes:
- name: antifraud
  nfs:
    path: /zpool8t/antifraud/uat
    server: 10.244.14.30
volumeMounts:
- name: antifraud
  mountPath: /opt

namespace: antifrauduat
project: antifrauduat

securityContext:
  runAsGroup: 0
  runAsUser: 0
  privileged: true