  vault:
    vaultTemplate: '{{- with secret  "secret/data/antifraud/uat/statuslogger/" }}{{ .Data.data.properties }}{{ end }}'
    vaultRole: "antifraud-statuslogger"
    vaultAddress: "https://vaulttest.otpbank.com.ua:443"
    vaultMountPath: "auth/uat-cluster/"
    appPropertiesPath: "/vault/secrets/application.properties"

  namespace: antifrauduat
  project: antifrauduat