  vault:
    vaultTemplate: '{{- with secret  "secret/data/antifraud/statuslogger/" }}{{ .Data.data.properties }}{{ end }}'
    vaultRole: "antifraud-statuslogger"
    vaultAddress: "https://vault.otpbank.com.ua:443"
    vaultMountPath: "auth/kubernetes/"
    appPropertiesPath: "/vault/secrets/application.properties"

  namespace: antifraudprod
  project: antifraudprod