vault:
  vaultTemplate: '{{- with secret  "secret/data/antifraud/uat/importer/" }}{{ .Data.data.properties }}{{ end }}'
  vaultRole: "antifraud-importer"
  vaultAddress: "https://vaulttest.otpbank.com.ua:443"
  vaultMountPath: "auth/uat-cluster/"
  appPropertiesPath: "/vault/secrets/application.properties"

#volumes:
#- name: antifraud
#  nfs:
#    path: /zpool8t/antifraud/uat
#   server: 10.244.14.30
#volumeMounts:
#- name: antifraud
#  mountPath: /opt

persistentVolume:
  name: antifraud-importer
  storage: 20Gi
  storageClassName: default
  namespace: antifrauduat
  accessModes:
    - ReadWriteMany
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: antifraud-importer
    volumeAttributes:
      source: "//uaatssrv02.raiffeisenbank.com.ua/antifraud/uat"
    nodeStageSecretRef:
      name: antifraud-volume
      namespace: antifrauduat

persistentVolumeClaim:
  name: antifraud-importer
  storage: 20Gi
  storageClassName: default
  namespace: antifrauduat
  accessModes:
    - ReadWriteMany

volumeMounts:
- name: antifraud-importer
  mountPath: /opt
volumes: 
- name: antifraud-importer
  persistentVolumeClaim:
    claimName: antifraud-importer

namespace: antifrauduat
project: antifrauduat