  vault:
    vaultTemplate: '{{- with secret  "secret/data/antifraud/dispatcher/" }}{{ .Data.data.properties }}{{ end }}'
    vaultRole: "antifraud-dispatcher"
    vaultAddress: "https://vault.otpbank.com.ua:443"
    vaultMountPath: "auth/kubernetes/"
    appPropertiesPath: "/vault/secrets/application.properties"

  namespace: antifraud
  project: antifraud