{{- range $key, $value := .Values.persistentVolumeClaim }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
spec:
  storageClassName: {{ .storageClassName }}
  capacity:
    storage: {{ .storage }}
  {{- with .csi }}   
  csi:
     {{- toYaml . | nindent 4 }}
  {{- end }} 
  {{- with .accessModes }}   
  accessModes:
     {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}