vault: 
  vaultTemplate: '{{- with secret  "secret/data/antifraud/uat/import/" }}{{ .Data.data.properties }}{{ end }}'
  vaultRole: "antifraud-import"
  vaultAddress: "https://vaulttest.otpbank.com.ua:443"
  vaultMountPath: "auth/test-cluster/"
  appPropertiesPath: "/vault/secrets/application.properties"

volumes:
- name: antifraud
  nfs:
    path: /zpool8t/antifraud/uat
    server: 10.244.14.30
volumeMounts:
- name: antifraud
  mountPath: /tmp