  vault: 
    vaultTemplate: '{{- with secret  "secret/data/antifraud/import/" }}{{ .Data.data.properties }}{{ end }}'
    vaultRole: "antifraud-import"
    vaultAdress: "https://vault.otpbank.com.ua:443"
    vaultMountPath: "auth/kubernetes/"
    appPropertiesPath: "/vault/secrets/application.properties"